/* JARVIS SYNC FILE — regenerated by Claude after every logged session. Do not edit by hand. */
window.JARVIS_DATA = {
  synced: "2026-07-23",
  examTarget: "week of Sep 21, 2026 (push: Sep 7)",
  floor: 8,
  weeklyNeed: 10,
  weekStart: "2026-07-20",
  hoursThisWeek: 0,
  lastSession: "2026-07-16",
  courseLeft: 54,
  position: "Fundamentals L3 Ch2 done — next: L3 Ch3 Group RE Investment Forms",
  tasks: [
    "Fri = Anchor #1 (~4 hrs): finish L3 Ch3, into L4",
    "Sun = Anchor #2 (~4 hrs): push Fundamentals",
    "Sat = bonus block to hit 10",
    "Report L3 Ch2 quiz score to Rune",
    "Floor 8 / goal 10 — RE gets protected slots, no full-week gaps"
  ],
  quiz: [
    {q:"What is the purpose of CC&Rs placed on a condominium by a developer?",a:["To protect developers from lawsuits","To inform the city of the development","To keep the development in good condition and preserve its value","To restrict the general public from entering"],c:2,why:"CC&Rs exist to preserve condition and value. You had 'inform the city' selected on tonight's quiz — this one owes you."},
    {q:"In Washington, a timeshare is a right to occupy a unit during:",a:["Two or more periods over two years","Three or more separate periods over at least three years","Any recurring annual week","Five or more periods over five years"],c:1,why:"WA statute: 3+ separate time periods over a period of at least 3 years, including renewal options."},
    {q:"A condominium owner holds:",a:["Shares in a corporation plus a lease","A separate interest in the unit and an undivided interest in common areas","A license to occupy","Only the airspace of the unit"],c:1,why:"Condo = separate unit interest + undivided common-area interest. Shares + proprietary lease = co-op."},
    {q:"In a housing co-op, the resident owns:",a:["The unit as real property","Shares in the corporation that owns the building","A timeshare estate","A tenancy in common with neighbors"],c:1,why:"The corporation owns the building; residents own shares (personal property) plus a proprietary lease."},
    {q:"A subdivision containing homes AND nonresidential real estate, departing from normal zoning, is a:",a:["Condominium regime","Planned unit development (PUD)","Cooperative","Timeshare project"],c:1,why:"PUD — recreational facilities may be co-owned by lot owners as tenants in common."},
    {q:"A right of occupancy in a timeshare project coupled with an estate in real property is a timeshare:",a:["Use","License","Estate","Membership"],c:2,why:"'Coupled with an estate' = timeshare ESTATE. Not coupled = timeshare USE (license/contract right)."},
    {q:"In Washington, who is responsible for condo window maintenance and replacement?",a:["Always the HOA","Always the unit owner","Whoever owns them per the CC&Rs — ownership MUST be explicitly spelled out","The developer for 10 years"],c:2,why:"WA-specific rule: window ownership must be explicit in the CC&Rs; the owner named there maintains and replaces them."},
    {q:"A fourplex residence is BEST classified as:",a:["Commercial property","Multifamily residential","Industrial property","Mixed-use property"],c:1,why:"1–4 units = residential (multifamily). 5+ units = commercial. This was on your miss list."},
    {q:"Which is a PHYSICAL characteristic of land?",a:["Scarcity","Situs (area preference)","Indestructibility","Improvements"],c:2,why:"Physical: immobility, indestructibility, uniqueness. The others are economic characteristics."},
    {q:"A tenant's cultivated crops that remain personal property even after sale of the land are called:",a:["Appurtenances","Emblements","Fixtures","Trade chattels"],c:1,why:"Emblements (fructus industriales) stay personal property; the tenant may re-enter to harvest."},
    {q:"The MOST important test of whether an item is a fixture is:",a:["Cost of the item","Method of attachment","Intention of the person who attached it","Age of the item"],c:2,why:"Intention is the controlling test; method, adaptability, and agreement are supporting evidence."},
    {q:"The highest and most complete form of ownership is:",a:["Fee simple determinable","Life estate","Fee simple absolute","Leasehold estate"],c:2,why:"Fee simple absolute — full bundle of rights, indefinite duration, freely transferable."},
    {q:"A life estate measured by the life of someone OTHER than the holder is called:",a:["Remainder estate","Pur autre vie","Reversionary estate","Estate at will"],c:1,why:"Pur autre vie = 'for another's life.' The named third party's life is the measuring stick."},
    {q:"Which form of co-ownership includes the right of survivorship?",a:["Tenancy in common","Joint tenancy","Tenancy in severalty","Ownership in trust"],c:1,why:"Joint tenancy: four unities (time, title, interest, possession) + survivorship."},
    {q:"Washington is a ______ state for marital ownership of property.",a:["Common law","Community property","Dower and curtesy","Elective share"],c:1,why:"WA is a community-property state — property acquired during marriage is presumed owned 50/50."},
    {q:"Two investors own unequal shares of a property with NO survivorship rights. This is:",a:["Joint tenancy","Tenancy in common","Community property","Severalty"],c:1,why:"Tenancy in common allows unequal shares and passes by will — no survivorship."},
    {q:"A warehouse used for product distribution is classified as:",a:["Commercial","Industrial","Rural","Special-purpose"],c:1,why:"Industrial = manufacturing, warehousing, storage, distribution, data centers."},
    {q:"The bundle of rights includes all of the following EXCEPT:",a:["Right of disposition","Right of exclusion","Right of taxation","Right of enjoyment"],c:2,why:"Taxation is a GOVERNMENT power. Bundle: possession, control, exclusion, enjoyment, disposition."},
    {q:"Ownership by one person alone is called tenancy in:",a:["Common","Severalty","Entirety","Partnership"],c:1,why:"Severalty — ownership is 'severed' from everyone else. One owner."}
  ]
};
