/* JARVIS SYNC FILE — regenerated by Claude after every logged session. Do not edit by hand. */
window.JARVIS_DATA = {
  synced: "2026-07-16",
  examTarget: "week of Aug 24, 2026",
  floor: 12,
  weeklyNeed: 13,
  weekStart: "2026-07-13",
  hoursThisWeek: 1.7,
  lastSession: "2026-07-14",
  courseLeft: 55,
  position: "Fundamentals L3 — after Use-Based Properties",
  tasks: [
    "Log study hours Wed–Sun — recover the week",
    "Continue Fundamentals Level 3",
    "Create PrepAgent account (check email)",
    "Register PSI student account",
    "Verify PSI exam fee ($138 vs $210)"
  ],
  quiz: [
    {q:"A fourplex residence is BEST classified as:",a:["Commercial property","Multifamily residential","Industrial property","Mixed-use property"],c:1,why:"1–4 units = residential (multifamily). 5+ units = commercial. This was on your miss list."},
    {q:"Which is a PHYSICAL characteristic of land?",a:["Scarcity","Situs (area preference)","Indestructibility","Improvements"],c:2,why:"Physical: immobility, indestructibility, uniqueness. The others are economic characteristics."},
    {q:"A tenant's cultivated crops that remain personal property even after sale of the land are called:",a:["Appurtenances","Emblements","Fixtures","Trade chattels"],c:1,why:"Emblements (fructus industriales) stay personal property; the tenant may re-enter to harvest."},
    {q:"The MOST important test of whether an item is a fixture is:",a:["Cost of the item","Method of attachment","Intention of the person who attached it","Age of the item"],c:2,why:"Intention is the controlling test; method, adaptability, and agreement are supporting evidence."},
    {q:"The highest and most complete form of ownership is:",a:["Fee simple determinable","Life estate","Fee simple absolute","Leasehold estate"],c:2,why:"Fee simple absolute — full bundle of rights, indefinite duration, freely transferable."},
    {q:"A life estate measured by the life of someone OTHER than the holder is called:",a:["Remainder estate","Pur autre vie","Reversionary estate","Estate at will"],c:1,why:"Pur autre vie = 'for another's life.' The named third party's life is the measuring stick."},
    {q:"Which form of co-ownership includes the right of survivorship?",a:["Tenancy in common","Joint tenancy","Tenancy in severalty","Ownership in trust"],c:1,why:"Joint tenancy: four unities (time, title, interest, possession) + survivorship. Tenancy in common has neither."},
    {q:"Washington is a ______ state for marital ownership of property.",a:["Common law","Community property","Dower and curtesy","Elective share"],c:1,why:"WA is a community-property state — property acquired during marriage is presumed owned 50/50."},
    {q:"Two investors own unequal shares of a property with NO survivorship rights. This is:",a:["Joint tenancy","Tenancy in common","Community property","Severalty"],c:1,why:"Tenancy in common allows unequal shares and passes by will — no survivorship."},
    {q:"A warehouse used for product distribution is classified as:",a:["Commercial","Industrial","Rural","Special-purpose"],c:1,why:"Industrial = manufacturing, warehousing, storage, distribution, data centers. Watch this vs. commercial — it was a weak-spot category."},
    {q:"The bundle of rights includes all of the following EXCEPT:",a:["Right of disposition","Right of exclusion","Right of taxation","Right of enjoyment"],c:2,why:"Taxation is a GOVERNMENT power, not an owner's right. Bundle: possession, control, exclusion, enjoyment, disposition."},
    {q:"Ownership by one person alone is called tenancy in:",a:["Common","Severalty","Entirety","Partnership"],c:1,why:"Severalty — ownership is 'severed' from everyone else. One owner."}
  ]
};
